name: CI/CD Java (Spring Boot) en Azure

on:
  pull_request:
    branches: [ "main" ]
    types: [ closed ]

env:
  SPRING_PROFILE_ACTIONS: prod

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    name: Deploy to Azure
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Configurar Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Dar permisos de ejecución al archivo gradlew
        run: chmod +x ./gradlew

      - name: Build con Gradle
        run: ./gradlew build -x test

      - name: Deploy a Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: "testing-environments"
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: build/libs/*.jar
